services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception


  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - inception

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

networks:
  inception:
    driver: bridge
