secrets:
  mysql_password:
    file: ../secrets/mysql_password
  mysql_root_password:
    file: ../secrets/mysql_root_password
  wp_admin_email:
    file: ../secrets/wp_admin_email
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_password:
    file: ../secrets/wp_admin_password

services:
  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    secrets:
      - mysql_password
      - mysql_root_password
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    secrets:
      - mysql_password
      - wp_admin_email
      - wp_admin_user
      - wp_admin_password
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - inception

  nginx:
    image: nginx:1.0
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception

volumes:
  db_data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/mariadb"
      o: bind
  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/wordpress"
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

