services:

  mariadb:
    container_name: mariadb
#    secrets:
#      - MYSQL_ROOT_PASSWORD
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 15s
      timeout: 10s
      retries: 10

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - inception


  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

networks:
  inception:
    driver: bridge

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
