include:

services:
  mariadb:
    image: mariadb
    container_name: mariadb
#    secrets:
#      - MYSQL_ROOT_PASSWORD
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - inception
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception

volumes:
  db_data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/mariadb"
      o: bind
  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/wordpress"
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
